### ISSUE TITLE
Binary plist from Monterey beta is failing to parse

### ISSUE THREAD

**Issue by mrthaggar** [claunia/plist-cil#71]
I've just tried reading a binary plist from the OSX Monterey beta, and the parse operation is failing:

`Failed to read plist data - Array dimensions exceeded supported range. -    at Claunia.PropertyList.BinaryPropertyListParser.DoParse(ReadOnlySpan`1 bytes)
   at Claunia.PropertyList.BinaryPropertyListParser.Parse(Byte[] data)
   at Claunia.PropertyList.PropertyListParser.Parse(Byte[] bytes)
   at myCallingCode`

Unfortunately, I cannot include the data as it contains personal information.  

So I was just wondering if you were aware of any issues with binary plists on Monterey?

**Comment by claunia** [comment]
Uhm, no, your is the first report of such a thing.

Can you share it privately to me only to check it?
If not, can you remove the private data and see if it still fails?

**Comment by mrthaggar** [comment]
Hey,

The data came from an Apple Keychain, but I've been told it's testing data, so if you can take a look, I'd appreciate it.

Thanks
________________________________

**Comment by mrthaggar** [comment]
Hey,

Just wondered if you had a chance to look at this yet?

Not rushing, just wanted to make sure I'm not using garbage data, and it's nothing to do with your library.

Thanks
________________________________
